// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:df23e9d6-fdac-43e2-a523-f997fc730356",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_AagnY4IqD",
    "aws_user_pools_web_client_id": "28mbbhdcam02svd47acssv114s",
    "aws_user_files_s3_bucket": "roseedition63af9e0450e54baf8c8ad8f4e96412d9",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
